image: Visual Studio 2017
environment:
  deploy_key:
    secure: 81b06hbrPXtgwahsu5Zqh+vemVUZ+LhRKR84h28Jaw71A5xgj1hIhUsT9PpiwpfahxbfhPpvPPazWZhtGYMVDf4nX1B7m440tMLwbTwo51IyjBcyR19GXj0W1AYrH+9UfeCycZ0csv7j/A4yJYZPLeVQ6huffLHvq1v8mSr7Dy4CY018mOKrDThgD79MbBXS+oYfxPZlBSPA3mLZk20cAW/0/yFNu6xs5vImuqdaYeIn4MTo2t3iFAOtT0MUHPGpOrrWqkib05lakgqqPhxNl/jKWoqP7z0fGP8joSMsnATYM0Yyf//NNBSRxRV0v+VObctgSpWKB+siN5l3j5FLln+jy4VCSLTHfDa0a4hKVsZkjGAi0NzAZVmG942NmMGVqsWb/mq3QrQuyuFSwa63/0fV1OEgWLRbDXWpnOE7DnjuDpFaj2MeOErmuMz6SHF8tO9WPUze2sRR/QZSO+uOQMzgwcugj7iH8lWbNqZg6Zk6tJW4vraSSeDyU5DM92kGMqVe4us2jgEAV3ldFtzRhCpWyElqdjbtbdGLy/wdvjqfkm3YoAYxsFpMVs+Uhj8Txv+TiAJJA+tzoPMSsdb9Puo7bHlyuqluX2JuxnJ47eWAWBxywrmZygykmXe1lIBJuRZHHBaVUqUoPzzCnsGZX5FMF7ktnXy6K+Z++DAovj+3sglmPTf4IHv5FvTv8OKS
  matrix:
    - cygwin_setup: https://cygwin.com/setup-x86.exe
      release_branch: release-x86
    - cygwin_setup: https://cygwin.com/setup-x86_64.exe
      release_branch: release-x86_64
cache:
  - C:\cygwin-build\home\appveyor\stat
install:
  - ps: |
      rm -Recurse -Force C:/cygwin, C:/cygwin64, 'C:/Program Files/Git'
      Invoke-WebRequest -Uri $env:cygwin_setup -OutFile cygwin.exe
      start -Wait ./cygwin.exe "-qng -R C:/cygwin-build -s http://cygwin.mirror.constant.com -P git -P gettext -P openssh -P gcc-core -P make -P automake -P autoconf -P libtool -P libpcre-devel -P libcares-devel -P libev-devel -P libsodium-devel -P mbedtls-devel"
build_script:
  - ps: |
      if ($env:enable_rdp -eq "true") {
          $blockRdp = $true;
          iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      }
  - C:/cygwin-build/bin/bash.exe build.sh
