image: Visual Studio 2017
environment:
  matrix:
    - cygwin_path: C:\cygwin
      cygwin_setup: setup-x86.exe
    - cygwin_path: C:\cygwin64
      cygwin_setup: setup-x86_64.exe
install:
    - ps: $env:cygwin_path\$env:cygwin_setup -qn -R $env:cygwin_path -s http://cygwin.mirror.constant.com -l $env:cygwin_path\var\cache\setup -P libpcre-devel -P libcares-devel -P libev-devel -P libsodium-devel -P mbedtls-devel
build_script:
    - ps: $env:cygwin_path\bin\bash.exe build.sh
