image: Visual Studio 2017
environment:
  deploy_key:
    secure: 81b06hbrPXtgwahsu5Zqh+vemVUZ+LhRKR84h28Jaw71A5xgj1hIhUsT9PpiwpfahxbfhPpvPPazWZhtGYMVDf4nX1B7m440tMLwbTwo51IyjBcyR19GXj0W1AYrH+9UfeCycZ0csv7j/A4yJYZPLeVQ6huffLHvq1v8mSr7Dy4CY018mOKrDThgD79MbBXS+oYfxPZlBSPA3mLZk20cAW/0/yFNu6xs5vImuqdaYeIn4MTo2t3iFAOtT0MUHPGpOrrWqkib05lakgqqPhxNl/jKWoqP7z0fGP8joSMsnATYM0Yyf//NNBSRxRV0v+VObctgSpWKB+siN5l3j5FLln+jy4VCSLTHfDa0a4hKVsZkjGAi0NzAZVmG942NmMGVqsWb/mq3QrQuyuFSwa63/0fV1OEgWLRbDXWpnOE7DnjuDpFaj2MeOErmuMz6SHF8tO9WPUze2sRR/QZSO+uOQMzgwcugj7iH8lWbNqZg6Zk6tJW4vraSSeDyU5DM92kGMqVe4us2jgEAV3ldFtzRhCpWyElqdjbtbdGLy/wdvjqfkm3YoAYxsFpMVs+Uhj8Txv+TiAJJA+tzoPMSsdb9Puo7bHlyuqluX2JuxnJ47eWAWBxywrmZygykmXe1lIBJuRZHHBaVUqUoPzzCnsGZX5FMF7ktnXy6K+Z++DAovj+3sglmPTf4IHv5FvTv8OKS
  cygwin_db: C:/cygwin-build/etc/setup
  matrix:
    - cygwin_setup: C:/cygwin/setup-x86.exe
      release_branch: release-x86
    - cygwin_setup: C:/cygwin64/setup-x86_64.exe
      release_branch: release-x86_64
cache:
  - C:\cygwin-build
install:
  - ps: |
      if (Test-Path $env:cygwin_db/installed.db) {
          cp $env:cygwin_db/installed.db $env:cygwin_db/old.db
      } else {
          echo "No existing Cygwin install detected."
      }
      start -Wait $env:cygwin_setup "-qng -R C:/cygwin-build -s http://cygwin.mirror.constant.com -P git -P openssh -P gcc-core -P make -P automake -P autoconf -P libtool -P libpcre-devel -P libcares-devel -P libev-devel -P libsodium-devel -P mbedtls-devel"
      if ((Test-Path $env:cygwin_db/old.db) -and !(compare (cat $env:cygwin_db/installed.db) (cat $env:cygwin_db/old.db))) {
          $env:APPVEYOR_CACHE_SKIP_SAVE = "true"
          echo "Cygwin already up-to-date, cache update skipped."
      }
build_script:
  - ps: |
      iex "C:/cygwin-build/bin/bash.exe build.sh"
      $host.SetShouldExit($LastExitCode)
deploy_script:
  - ps: |
      iex "C:/cygwin-build/bin/bash.exe deploy.sh"
      $host.SetShouldExit($LastExitCode)
