on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x86_64]
    runs-on: windows-2019
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@master
      - shell: powershell
        env:
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          ARCH: ${{ matrix.arch }}
        run: |
          Invoke-WebRequest -Uri https://cygwin.com/setup-${{ matrix.arch }}.exe -OutFile cygwin.exe
          start -Wait .\cygwin.exe "-qng -R cygwin -s http://cygwin.mirror.constant.com -P git -P gettext -P openssh -P gcc-core -P make -P automake -P autoconf -P libtool -P libpcre-devel -P libcares-devel -P libev-devel -P libsodium-devel -P mbedtls-devel"
          .\cygwin\bin\bash.exe build.sh
